<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
		<EmbeddedResource Include="Roms\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
		<PackageReference Include="JAJ.Packages.MiniAudioEx" Version="2.6.7" />

		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Atem.App\Atem.App.csproj" />
		<ProjectReference Include="..\Atem.Core\Atem.Core.csproj" />
	</ItemGroup>
</Project>