name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Restore Dependencies
        run: |
          dotnet restore src/Atem.Core/Atem.Core.csproj --no-cache
          dotnet restore src/Atem/Atem.csproj --no-cache
      - name: Build
        run: dotnet build -c Release --no-restore